{
 "title": "Aliyun-SLb-internal",
 "description": "阿里云kubernetes slb监控",
 "tags": [ "aliyun-slb" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "数据流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "describe": "实例每秒出bit数",
     "dimensions": [ "lb-2zejtfgs5fpqb9hsgypuv" ],
     "metric": "InstanceTrafficTX",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    },
    {
     "describe": "实例每秒入bit数",
     "dimensions": [ "lb-2zejtfgs5fpqb9hsgypuv" ],
     "metric": "InstanceTrafficRX",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "数据包数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "describe": "实例每秒出包数",
     "dimensions": [ "lb-2zejtfgs5fpqb9hsgypuv" ],
     "metric": "InstancePacketTX",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    },
    {
     "describe": "实例每秒入包数",
     "dimensions": [ "lb-2zejtfgs5fpqb9hsgypuv" ],
     "metric": "InstancePacketRX",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "连接数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "describe": "实例每秒活跃连接数",
     "dimensions": [ "lb-2zejtfgs5fpqb9hsgypuv" ],
     "metric": "InstanceActiveConnection",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    },
    {
     "describe": "实例每秒非活跃连接数",
     "dimensions": [ "lb-2zejtfgs5fpqb9hsgypuv" ],
     "metric": "InstanceInactiveConnection",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    },
    {
     "describe": "实例每秒新建连接数",
     "dimensions": [ "lb-2zejtfgs5fpqb9hsgypuv" ],
     "metric": "InstanceNewConnection",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    },
    {
     "describe": "实例每秒最大并发连接数",
     "dimensions": [ "lb-2zejtfgs5fpqb9hsgypuv" ],
     "metric": "InstanceMaxConnection",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    },
    {
     "describe": "实例每秒丢失连接数",
     "dimensions": [ "lb-2zejtfgs5fpqb9hsgypuv" ],
     "metric": "InstanceDropConnection",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "连接数使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "describe": "最大连接数使用率",
     "dimensions": [ "lb-2zejtfgs5fpqb9hsgypuv" ],
     "metric": "InstanceMaxConnectionUtilization",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    },
    {
     "describe": "新建连接数使用率",
     "dimensions": [ "lb-2zejtfgs5fpqb9hsgypuv" ],
     "metric": "InstanceNewConnectionUtilization",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "后端ECS实例健康状态",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "后端异常ECS实例个数",
     "dimensions": [ "lb-2zejtfgs5fpqb9hsgypuv" ],
     "metric": "UnhealthyServerCount",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    },
    {
     "describe": "后端健康ECS实例个数",
     "dimensions": [ "lb-2zejtfgs5fpqb9hsgypuv" ],
     "metric": "HeathyServerCount",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  }
 ]
}